baseURL = "https://rakam.io/"
copyright = "&copy; Copyright notice"
languageCode = "en-us"
title = "rakam.io - Analyze Your Customer Data in a Seamless Way"
[params]
author = "Burak Emre Kabakci"
logo= "/images/new-logo.svg"
authorwebsite = "buremba.com"
subtitle = "Product analytics tool for funnel, retention and segmentation. Looker Alternative for user event analytics."
avatar = "/me.jpg"
contact = "mailto:emrekabakci@gmail.com"
disqus = "buremba"
facebook = "rakamio"
github = "rakam-io"
linkedin = "burak-emre-kabakcÄ±-15b2bb33"
twitter = "iorakam"
enableRobotsTXT = "true"