[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
  command = "hugo server -wD -d dev "

[[redirects]]
  from = "/blog/*"
  to = "http://ghost.warehouse.35.244.188.74.xip.io/:splat"
  status = 200
  force = true