[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
  command = "hugo server -wD -d dev "

[[redirects]]
  from = "/blog4/*"
  to = "https:/blog.rakam.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https:/blog.rakam.io/:splat"
  status = 200
  force = true